export const products = [
  {
    img: "product-img-1",
    id: 1,
    title: "Краска Wallquest, Brownsone MS90102",
    price: "3300 ₽",
    type: ["new", "availability", "contract"],
    instock: 6,
  },
  {
    img: "product-img-2",
    id: 2,
    title: "Краска Wallquest, Brownsone MS90102",
    price: "3400 ₽",
    type: ["availability", "sale"],
    instock: 3,
  },
  {
    img: "product-img-1",
    id: 3,
    title: "Краска Wallquest, Brownsone MS90102",
    price: "3500 ₽",
    type: ["contract", "new"],
    instock: false,
  },
  {
    img: "product-img-2",
    id: 4,
    title: "Краска Wallquest, Brownsone MS90102",
    price: "3700 ₽",
    type: ["exclusive", "new"],
    instock: 88,
  },
  {
    img: "product-img-2",
    id: 5,
    title: "Краска Wallquest, Brownsone MS90102",
    price: "3600 ₽",
    type: ["sale", "availability"],
    instock: 10,
  },
  {
    img: "product-img-1",
    id: 6,
    title: "Краска Wallquest, Brownsone MS90102",
    price: "3800 ₽",
    type: ["new"],
    instock: 1,
  },
  {
    img: "product-img-2",
    id: 7,
    title: "Краска Wallquest, Brownsone MS90102",
    price: "4000 ₽",
    type: ["new", "availability", "exclusive"],
    instock: false,
  },
  {
    img: "product-img-1",
    id: 8,
    title: "Краска Wallquest, Brownsone MS90102",
    price: "3900 ₽",
    type: ["contract", "sale"],
    instock: 5,
  },
  {
    img: "product-img-2",
    id: 9,
    title: "Краска Wallquest, Brownsone MS90102",
    price: "4200 ₽",
    type: ["exclusive", "new"],
    instock: 5,
  },
  {
    img: "product-img-2",
    id: 10,
    title: "Краска Wallquest, Brownsone MS90102",
    price: "4100 ₽",
    type: ["sale"],
    instock: 15,
  },
  {
    img: "product-img-1",
    id: 11,
    title: "Краска Wallquest, Brownsone MS90102",
    price: "4400 ₽",
    type: ["new"],
    instock: 12,
  },
  {
    img: "product-img-2",
    id: 12,
    title: "Краска Wallquest, Brownsone MS90102",
    price: "4500 ₽",
    type: ["availability"],
    instock: 8,
  },
  {
    img: "product-img-1",
    id: 13,
    title: "Краска Wallquest, Brownsone MS90102",
    price: "4300 ₽",
    type: ["contract"],
    instock: 7,
  },
  {
    img: "product-img-2",
    id: 14,
    title: "Краска Wallquest, Brownsone MS90102",
    price: "4600 ₽",
    type: ["exclusive"],
    instock: 9,
  },
  {
    img: "product-img-2",
    id: 15,
    title: "Краска Wallquest, Brownsone MS90102",
    price: "4700 ₽",
    type: ["sale"],
    instock: 2,
  },
];
