export const products = [
  {
    img: "product-img-1",
    title: "Краска Wallquest, Brownsone MS90102",
    price: "3300 ₽",
    type: ["new"],
    instock: 6,
  },
  {
    img: "product-img-2",
    title: "Краска Wallquest, Brownsone MS90102",
    price: "3400 ₽",
    type: ["availability"],
    instock: 3,
  },
  {
    img: "product-img-1",
    title: "Краска Wallquest, Brownsone MS90102",
    price: "3500 ₽",
    type: ["contract"],
    instock: 10,
  },
  {
    img: "product-img-2",
    title: "Краска Wallquest, Brownsone MS90102",
    price: "3700 ₽",
    type: ["exclusive"],
    instock: 88,
  },
  {
    img: "product-img-2",
    title: "Краска Wallquest, Brownsone MS90102",
    price: "3600 ₽",
    type: ["sale"],
    instock: 10,
  },
  {
    img: "product-img-1",
    title: "Краска Wallquest, Brownsone MS90102",
    price: "3800 ₽",
    type: ["new"],
    instock: 1,
  },
  {
    img: "product-img-2",
    title: "Краска Wallquest, Brownsone MS90102",
    price: "4000 ₽",
    type: ["availability"],
    instock: 0,
  },
  {
    img: "product-img-1",
    title: "Краска Wallquest, Brownsone MS90102",
    price: "3900 ₽",
    type: ["contract"],
    instock: 5,
  },
  {
    img: "product-img-2",
    title: "Краска Wallquest, Brownsone MS90102",
    price: "4200 ₽",
    type: ["exclusive"],
    instock: 5,
  },
  {
    img: "product-img-2",
    title: "Краска Wallquest, Brownsone MS90102",
    price: "4100 ₽",
    type: ["sale"],
    instock: 15,
  },
  {
    img: "product-img-1",
    title: "Краска Wallquest, Brownsone MS90102",
    price: "4400 ₽",
    type: ["new"],
    instock: 12,
  },
  {
    img: "product-img-2",
    title: "Краска Wallquest, Brownsone MS90102",
    price: "4500 ₽",
    type: ["availability"],
    instock: 8,
  },
  {
    img: "product-img-1",
    title: "Краска Wallquest, Brownsone MS90102",
    price: "4300 ₽",
    type: ["contract"],
    instock: 7,
  },
  {
    img: "product-img-2",
    title: "Краска Wallquest, Brownsone MS90102",
    price: "4600 ₽",
    type: ["exclusive"],
    instock: 9,
  },
  {
    img: "product-img-2",
    title: "Краска Wallquest, Brownsone MS90102",
    price: "4700 ₽",
    type: ["sale"],
    instock: 2,
  },
];
